### ISSUE TITLE
numbers in name — edge case

### ISSUE THREAD

**Issue by alexeiva** [codeman38/PressStart2P#2]
Marc's QA script output:

```
**Check family name has only ASCII characters**
ERROR: Font family "Press Start 2P", contains numbers, slashes or dashes.
```

fontbakery-check-ttf.py error output:

```
ERROR    [FONT_FAMILY_NAME(1):MACINTOSH(1)] entry: expected 'Press Start2 P' but got 'Press Start 2P'  
ERROR    [FULL_FONT_NAME(4):MACINTOSH(1)] entry: expected 'Press Start2 P Regular' but got 'Press Start 2P Regular'  
ERROR    [FONT_FAMILY_NAME(1):WINDOWS(3)] entry: expected 'Press Start2 P' but got 'Press Start 2P'  
ERROR    [FULL_FONT_NAME(4):WINDOWS(3)] entry: expected 'Press Start2 P Regular' but got 'Press Start 2P Regular' 
```

/cc @davelab6 @m4rc1e How should I proceed?

Font validates fine:

![screen shot 2016-10-14 at 17 26 59](https://cloud.githubusercontent.com/assets/16634089/19406022/7094a8f4-9233-11e6-9460-542d486724ee.png)

**Comment by m4rc1e** [comment]
Hey Alexei,

We had this problem with VT323. We decided that a font familiy's name should not start with a number only.

I need to update this test. The issue was filed a while back on my repo, [#16](https://github.com/m4rc1e/mf-glyphs-scripts/issues/16).

Please ignore this, you're fine.

Cheers,
Marc

**Comment by felipesanches** [comment]
@alexeiva This can be closed now, as the check was fixed on fontbakery.

**Comment by alexeiva** [comment]
Just updated fb using 

`cd ~/src/github.com/googlefonts/fontbakery && git pull origin master && cd ~`
`sudo -H pip install --upgrade git+https://github.com/googlefonts/fontbakery.git`

Am I updating fb properly?

and still get this. 

```
ERROR    [FONT_FAMILY_NAME(1):MACINTOSH(1)] entry: expected 'Press Start2 P' but got 'Press Start 2P'  
ERROR    [FULL_FONT_NAME(4):MACINTOSH(1)] entry: expected 'Press Start2 P Regular' but got 'Press Start 2P Regular'  
ERROR    [FONT_FAMILY_NAME(1):WINDOWS(3)] entry: expected 'Press Start2 P' but got 'Press Start 2P'  
ERROR    [FULL_FONT_NAME(4):WINDOWS(3)] entry: expected 'Press Start2 P Regular' but got 'Press Start 2P Regular'  
```

I am okay to ignore this error, as it appears just in this font.

**Comment by felipesanches** [comment]
If you still face the problem then the fb issue was not properly fixed. Even though you may be willing to ignore the issue, fb still has an issue that needs to be fixed.
